### ISSUE TITLE
Solve large format download issue

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#905]
Two methods: 

1. In our info.json: Provide `maxWidth` in the info.json and UV won't offer a download higher than that allows.

or 

2. In the UV config: `maxImageWidth` does this for us as if asserted by info.json; maybe a quicker fix?  https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/config/en-GB.json#L104

**Comment by cbeer** [comment]
What is the "large  format download issue"?

**Comment by mejackreed** [comment]
@snydman is there a sufficiently large size that we can configure to for a user, where they may not be getting full resolution, but it is "good enough"

**Comment by mejackreed** [comment]
I think the reference is to "this" issue https://github.com/sul-dlss/sul-embed/issues/739

Looking into it a bit this morning, I think the true solution is a tuning of our Cantaloupe instance. Right now it doesn't appear that `max_pixels` configured https://github.com/sul-dlss/puppet/blob/f42d3bd6db6b9a7b1b4e6fdc70508bc987afdb89/modules/profile/files/cantaloupe/cantaloupe.properties#L54 is being respected.

The info.json response is still returning too large sizes > 400000000 https://stacks.stanford.edu/image/iiif/st808xq5141%2Fst808xq5141_05_0001/info.json

A local install of Cantaloupe seems to handle this ok with a configured `max_pixels`. Thoughts @cbeer , @jcoyne ?

**Comment by jcoyne** [comment]
@mejackreed it's possible that this has been fixed since we last upgraded cantaloupe.  Maybe a round of upgrades is in order?

**Comment by cbeer** [comment]
I'm still unclear what the issue is. Are users crashing our infrastructure requesting large images, or.. are they just large?

**Comment by mejackreed** [comment]
I think the issue is this:

Users are requesting "very large images" which are conveyed in the info.json sizes as available. The image server is unable to respond to some of large requests. A quick review of some of the sizes in #739 shows that pixel requests of 129600000 and 287418816 succeeded, while  1792292774 (st808xq5141) fails. That `size` should have never been offered as the Cantaloupe.properties `max_pixels` should have restricted the sizes offered for a "big download".

I think this commit https://github.com/medusa-project/cantaloupe/commit/a51b1340b24389774c8f0a81125bf3be37ac8d17 fixes the issue we are seeing. So if we can upgrade to 3.4.2 or a release with this commit, I'm hoping this resolves with our current config.

**Comment by blalbrit** [comment]
To build on what @mejackreed said - UV only offers "full image" download or nothing. The old embed viewer allowed smaller size choices so when a very large image failed, we could direct users to one of the intermediary sizes. The users are doing the only action available to them - in the new embed, that happens to try to build a jpg from the jp2 that is too big for our infrastructure to process. My understanding is that it is the conversion from jp2 to jpg at very large sizes that is problematic and memory intensive.

Seems like there are a lot of ways to technically approach the problem, but from a user perspective the problem is: "the software says I can download this, and then it fails to download". Whether we solve it by capping the download size, offering intermediate smaller sizes, or other server-side approaches, we need to be able to deliver an image to a user when it is offered for download.

**Comment by mejackreed** [comment]
Agreed @blalbrit . My reasoning on approaching this at Cantaloupe is that manifests consumed by non-sul-embed users would still present the same errors.

**Comment by cbeer** [comment]
Here's the error cantaloupe throws when requesting very large images:

```
13:13:45.665 [ajp-apr-8009-exec-9] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET https://sul-imageserver-uat.stanford.edu/iiif/2/st%2F808%2Fxq%2F5141%2Fst808xq5141_05_0001.jp2/full/51200,/0/default.png [connection: close; host: sul-imageserver-uat.stanford.edu; user-agent: http.rb/3.3.0; content-length: 0]
13:13:45.666 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.r.AbstractResource - Identifier requested: st%2F808%2Fxq%2F5141%2Fst808xq5141_05_0001.jp2 -> decoded: st/808/xq/5141/st808xq5141_05_0001.jp2 -> slashes substituted: st/808/xq/5141/st808xq5141_05_0001.jp2
13:13:45.666 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.c.InfoService - getInfo(): retrieved info of st/808/xq/5141/st808xq5141_05_0001.jp2 from InfoCache
13:13:45.666 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.o.OperationList - applyNonEndpointMutations(): redactions are disabled; skipping.
13:13:45.666 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.o.OperationList - applyNonEndpointMutations(): overlays are disabled; skipping.
13:13:45.667 [ajp-apr-8009-exec-9] INFO  e.i.l.c.s.FilesystemSource - Resolved st/808/xq/5141/st808xq5141_05_0001.jp2 to /stacks/st/808/xq/5141/st808xq5141_05_0001.jp2
13:13:45.672 [ajp-apr-8009-exec-9] INFO  e.i.l.c.p.ProcessorConnector - FileSource -> FileProcessor connection between FilesystemSource and KakaduDemoProcessor
13:13:45.673 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.c.InfoService - getInfo(): retrieved info of st/808/xq/5141/st808xq5141_05_0001.jp2 from InfoCache
13:13:45.673 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.r.AbstractResource - X-Forwarded headers: Proto: HTTP; Host: null; Port: null; Path: 
13:13:45.673 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.r.AbstractResource - Base URI assembled: http://sul-imageserver-uat.stanford.edu
13:13:45.675 [ajp-apr-8009-exec-9] INFO  e.i.l.c.c.FilesystemCache - newOutputStream(): miss; caching st/808/xq/5141/st808xq5141_05_0001.jp2_scale:51200,,bicubic_encode:png_UNDEFINED_8
13:13:45.675 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.r.ImageRepresentation - Writing to the response & derivative cache simultaneously
13:13:45.675 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.KakaduDemoProcessor - Invoking kdu_expand -quiet -resilient -no_alpha -i /stacks/st/808/xq/5141/st808xq5141_05_0001.jp2 -o /var/cache/tomcat/temp/KakaduDemoProcessor-2189fe0c-9a79-4159-8a91-47fd495bb528.tif
13:13:45.680 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.c.TIFFImageReader - ImageIO plugin preferences: it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader, com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader
13:13:45.680 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.c.TIFFImageReader - Using it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader
13:13:45.680 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.c.TIFFImageReader - Ignoring metadata? true
13:13:45.682 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream - close(): closing stream for st/808/xq/5141/st808xq5141_05_0001.jp2_scale:51200,,bicubic_encode:png_UNDEFINED_8
13:13:45.682 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream - close(): deleting zero-byte file: /image-cache/cantaloupe/image/a1/8d/fc/a18dfc5c8ead6c3af1f7d6f82ec57890_6ad41eaafce5475a576929299d914fa8.png_ajp-apr-8009-exec-9.tmp
13:13:45.682 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.r.ImageRepresentation - write(): Invalid scanline stride
13:13:45.683 [ajp-apr-8009-exec-9] INFO  e.i.l.c.c.FilesystemCache - purge(OperationList): purging st/808/xq/5141/st808xq5141_05_0001.jp2_scale:51200,,bicubic_encode:png_UNDEFINED_8...
13:13:45.683 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.KakaduDemoProcessor - Invoking kdu_expand -quiet -resilient -no_alpha -i /stacks/st/808/xq/5141/st808xq5141_05_0001.jp2 -o /var/cache/tomcat/temp/KakaduDemoProcessor-2189fe0c-9a79-4159-8a91-47fd495bb528.tif
13:13:45.688 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.c.TIFFImageReader - ImageIO plugin preferences: it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader, com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader
13:13:45.689 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.c.TIFFImageReader - Using it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader
13:13:45.689 [ajp-apr-8009-exec-9] DEBUG e.i.l.c.p.c.TIFFImageReader - Ignoring metadata? true
13:13:45.692 [ajp-apr-8009-exec-9] ERROR o.r.C.Server - An exception occurred writing the response entity
java.lang.IllegalArgumentException: Invalid scanline stride
	at java.awt.image.ComponentSampleModel.getBufferSize(ComponentSampleModel.java:274)
	at java.awt.image.ComponentSampleModel.verify(ComponentSampleModel.java:252)
	at java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:170)
	at java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.awt.image.PixelInterleavedSampleModel.createCompatibleSampleModel(PixelInterleavedSampleModel.java:144)
	at javax.imageio.ImageTypeSpecifier.getSampleModel(ImageTypeSpecifier.java:1039)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.getDestination(TIFFImageReader.java:2127)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1727)
	at javax.imageio.ImageReader.read(ImageReader.java:939)
	at edu.illinois.library.cantaloupe.processor.codec.AbstractIIOImageReader.read(AbstractIIOImageReader.java:302)
	at edu.illinois.library.cantaloupe.processor.KakaduDemoProcessor.processInUnix(KakaduDemoProcessor.java:417)
	at edu.illinois.library.cantaloupe.processor.KakaduDemoProcessor.process(KakaduDemoProcessor.java:310)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:180)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:151)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:191)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:188)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2549)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2538)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
13:13:45.693 [ajp-apr-8009-exec-9] WARN  o.r.C.Server - Error while handling an HTTP server call
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
	at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:450)
	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:388)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:208)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:188)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2549)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2538)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by anarchivist** [comment]
Another report (documented on #739) of this is coming up. Let's get this onto the docket for our next maintenance/transition week.

**Comment by jkeck** [comment]
On a related note, while this does not resolve this issue, we are now offering the other download sizes that the IIIF Image API returns (as was intended).

**Comment by mejackreed** [comment]
Closing this as we are now limiting the sizes that can be downloading but also offering the jp2 for download
